version: "3"
services:
  api:
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - 3000:3000
    volumes:
      - .:/app:cached
      - bundle:/usr/local/bundle
      - temp:/app/vendor
      - temp:/app/tmp
      - temp:/app/.git
    depends_on:
      - db
    networks:
      - default
  db:
    image: mariadb
    platform: linux/x86_64
    ports:
      - 3306:3306
    volumes:
      - db-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password

volumes:
  bundle:
  temp:
  db-volume:
